<PageLayout>:
    orientation: "lr-tb"
    color_text: 0,0,1,1
    spacing: 10
    padding: 10

    Button:
        text: "1st"
        size_hint: None, .5
        width: 100
    Button:
        text: "hello "
        size_hint: None, .20
        width: 120
    Button:
        text: "1st"
        size_hint: None, .5
        width: 100
    Button:
        text: "hello "
        size_hint: None, .20
        width: 120

