<CustButton@Button>:
     font_size : 32
     color: 0,0,0,1
     size: 150, 50
     background_normal: ''
     background_down: '28.jpg'
     background_color: .88,.88,.88,1

     <HelloKivy>:
        CustomButton:
            text: "Random"
            pos: root.x, 200

     <CustomWidget>:
        CustomButton:
            text: "Random"
            pos: 200, root.y

     <CustomWidget>:
        CustomButton:
            text: "Random"
            pos: 200, 400